# Generated by Django 2.2.3 on 2019-07-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20190731_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='fro',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='to',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='verse',
            field=models.IntegerField(),
        ),
    ]
