# Generated by Django 2.2.3 on 2019-07-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='facebook',
            field=models.URLField(max_length=256),
        ),
        migrations.AlterField(
            model_name='team',
            name='twiter',
            field=models.URLField(max_length=256),
        ),
    ]
