# Generated by Django 2.2.3 on 2019-07-22 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190721_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='services',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.event', verbose_name='Event'),
        ),
    ]
