# Generated by Django 2.2.3 on 2019-07-22 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190722_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='db_event',
        ),
        migrations.AddField(
            model_name='event',
            name='Event',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 22, 19, 29, 22, 455764), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(),
        ),
    ]
