# Generated by Django 2.2.3 on 2019-07-22 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190722_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='album',
        ),
        migrations.AlterField(
            model_name='services',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 22, 19, 32, 48, 355551), verbose_name='date'),
        ),
    ]
