# Generated by Django 2.2.3 on 2019-07-22 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190722_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='img',
            field=models.ImageField(null=True, upload_to='pics/gallery'),
        ),
        migrations.AlterField(
            model_name='services',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 22, 19, 36, 2, 143032), verbose_name='date'),
        ),
    ]
