# Generated by Django 2.2.3 on 2019-07-22 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190722_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.ImageField(blank=True, height_field=200, null=True, upload_to='pics/about', width_field=200),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='img',
            field=models.ImageField(default=1, upload_to='pics/gallery'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 22, 21, 25, 31, 958924), verbose_name='date'),
        ),
    ]
