# Generated by Django 2.2.3 on 2019-07-22 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190722_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.ImageField(blank=True, height_field=200, upload_to='pics/about', width_field=200),
        ),
        migrations.AlterField(
            model_name='services',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 22, 23, 20, 27, 196157), verbose_name='date'),
        ),
    ]
