# Generated by Django 2.2.3 on 2019-07-23 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190722_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.ImageField(blank=True, default='pics/about/screenshot.png', upload_to='pics/about'),
        ),
        migrations.AlterField(
            model_name='services',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 23, 17, 28, 15, 585089), verbose_name='date'),
        ),
    ]
