# Generated by Django 2.2.3 on 2019-07-23 15:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190723_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='img',
            field=models.ImageField(default='pics/gallery/default.jpg', upload_to='pics/gallery'),
        ),
        migrations.AlterField(
            model_name='services',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 23, 17, 42, 44, 362102), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='services',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='services',
            name='img',
            field=models.ImageField(blank=True, default='pics/about/default.jpg', upload_to='pics/services'),
        ),
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ImageField(blank=True, default='pics/team/default.png', upload_to='pics/team'),
        ),
    ]
