# Generated by Django 2.2.3 on 2019-07-23 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190723_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.ImageField(blank=True, default='pics/about/default.jpg', upload_to='pics/about'),
        ),
        migrations.AlterField(
            model_name='services',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 23, 17, 53, 53, 133289), verbose_name='date'),
        ),
    ]
