# Generated by Django 2.2.3 on 2019-07-31 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190723_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 31, 18, 37, 37, 958623), verbose_name='date'),
        ),
    ]
