# Generated by Django 2.2.3 on 2019-07-31 16:46

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190731_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 31, 18, 46, 41, 914259), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=100),
        ),
    ]
