# Generated by Django 2.2.3 on 2019-07-31 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20190731_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 31, 19, 4, 11, 41417), verbose_name='date'),
        ),
    ]
