# Generated by Django 2.2.3 on 2019-08-01 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20190731_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='type',
        ),
        migrations.AlterField(
            model_name='services',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 1, 10, 14, 51, 834838), verbose_name='date'),
        ),
    ]
