# Generated by Django 2.2.3 on 2019-08-01 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20190801_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='day',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 1, 10, 22, 4, 914122), verbose_name='date'),
        ),
    ]
